Astro
znci/new-web pull request #9
Opened 2024-06-02 20:06 UTC by cerqiest

Port the entire site to Astro. Some bits should most likely be moved to their own components, but that can be pushed to later date. CSS reshuffling (to scope everything) should also be considered. If anybody can figure out why the RSS icon in the footer doesn't/has never worked, please do.

2024-06-02 21:06 UTC, TheUnium reviewed
lol

2024-06-02 21:16 UTC, zNotChill approved these changes
looks good enough to me

2024-06-02 21:27 UTC, TheUnium reviewed
looks good to me, just remove some commented out code, and should be god to go

2024-06-02 21:27 UTC, TheUnium commented on README.md
> +# Astro Starter Kit: Minimal
change readme from the default, doesnt matter that much, just a suggestion

2024-06-02 21:27 UTC, TheUnium commented on src/components/RSSSection.astro
> +    <!-- <div class="card">
remove commented code for now

2024-06-02 21:27 UTC, TheUnium commented on src/pages/index.astro
> +          <!-- <form
remove commented code

2024-06-02 21:37 UTC, TheUnium approved these changes
alright, looks good to me!

2024-06-02 21:43 UTC, blockarchitech requested changes
Overall fine - everything looks fine and works on my end. Please address the review comments, notably the contact form and some code style things, plus some of the front page content.

2024-06-02 21:43 UTC, blockarchitech commented on .github/workflows/deploy.yml
> +    branches: [main]
should probably change this to PR merge

2024-06-02 21:43 UTC, blockarchitech commented on .vscode/launch.json
> +{
This file should be gitignored as it can cause some issues if you don't have astro installed. Also unnecessary.

2024-06-02 21:43 UTC, blockarchitech commented on .vscode/settings.json
> +    "https://json.schemastore.org/github-workflow.json": "file:///Users/franciscocreque/repos/znci/new-web/.github/workflows/deploy.yml"
Maybe let's not use some random schema from some dude's PC? Does this even work?

2024-06-02 21:43 UTC, blockarchitech commented on README.md
> +
We really don't need credits in the README. GitHub already does this

2024-06-02 21:43 UTC, blockarchitech commented on astro.config.mjs
> +
random whitespace

2024-06-02 21:43 UTC, blockarchitech commented on src/components/solid/RSSFeed.tsx
> +      {feed.error && <span>RSS feed failed to load: {feed.error.message}</span>}
Fine? In the future we should probably add a log collector or something and give the user a generic error.

2024-06-02 21:43 UTC, blockarchitech commented on src/components/solid/RSSFeed.tsx
> +              <span class="tag tag-blue">NEW</span>
Is this added to every card?

2024-06-02 21:43 UTC, blockarchitech commented on src/content/members/01-znotchill.md
> +---
Is front matter abuse how astro does this?

2024-06-02 21:43 UTC, blockarchitech commented on src/content/projects/01-paint.md
> +---
We should probably change around some of our projects, as Acid isn't even a znci project and web is long dead.

2024-06-02 21:43 UTC, blockarchitech commented on src/env.d.ts
> +/// <reference path="../.astro/types.d.ts" />
What's the purpose of this file?

2024-06-02 21:43 UTC, blockarchitech commented on src/pages/404.astro
> +<style>
Why are we using <style> tags?

2024-06-02 21:43 UTC, blockarchitech commented on src/pages/index.astro
> +            Unfortunately, the contact form has been removed due to spam and
We should fix this, or add something new, before launching the astro site.

2024-06-02 21:46 UTC, TheUnium commented on src/env.d.ts
> +/// <reference path="../.astro/types.d.ts" />
ts declarations

2024-06-02 21:48 UTC, cerqiest commented on .github/workflows/deploy.yml
> +    branches: [main]
not everything will be/has been a pr merge

2024-06-02 21:48 UTC, blockarchitech commented on src/env.d.ts
> +/// <reference path="../.astro/types.d.ts" />
They are commented out.

2024-06-02 21:51 UTC, cerqiest commented on astro.config.mjs
> +
it's just to section off the code, it's not random

2024-06-02 21:52 UTC, cerqiest commented on src/components/solid/RSSFeed.tsx
> +              <span class="tag tag-blue">NEW</span>
yeah, it was that way in the original site

2024-06-02 21:52 UTC, blockarchitech commented on .github/workflows/deploy.yml
> +    branches: [main]
It should be!

2024-06-02 21:54 UTC, cerqiest commented on src/content/members/01-znotchill.md
> +---
collections can be json-based too, i just used markdown here. in the case of the projects, it'll likely be useful to maybe add some more details in the body

2024-06-02 21:54 UTC, cerqiest commented on src/content/projects/01-paint.md
> +---
you and @zNotChill can mess with this as you want

2024-06-02 21:55 UTC, cerqiest commented on src/env.d.ts
> +/// <reference path="../.astro/types.d.ts" />
just the way ts does it, this is normal

2024-06-02 21:55 UTC, blockarchitech commented on astro.config.mjs
> +
:shrug: It's two lines

2024-06-02 21:55 UTC, cerqiest commented on src/pages/404.astro
> +<style>
it's a one-off page that needs its own styles to do 2 things

2024-06-02 21:56 UTC, cerqiest commented on src/pages/404.astro
> +<style>
styles are compiled by astro anyways so the only diff is where the styles are located

2024-06-02 21:58 UTC, cerqiest commented on .github/workflows/deploy.yml
> +    branches: [main]
it's just to cover all our bases, it's a trivial change anyways

2024-06-02 21:58 UTC, TheUnium commented on src/env.d.ts
> +/// <reference path="../.astro/types.d.ts" />
triple slashes (///) indicate a directive, not a comment which are prefixed with double slashes (//)

2024-06-02 21:59 UTC, blockarchitech commented on src/env.d.ts
> +/// <reference path="../.astro/types.d.ts" />
Ah, here's me thinking /// was jsdoc. I should take a break from swift.

2024-06-29 19:51 UTC, blockarchitech approved these changes
LGTM

2024-06-29 19:51 UTC, merged